## Imports

In [1]:
import pickle

In [2]:
import numpy as np

In [3]:
import torch.nn as nn
import torch

In [4]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /usr/share/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /usr/share/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /usr/share/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /usr/share/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /usr/share/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /usr/share/nltk_data...
[nltk_data]    | Downloading pa

True

In [5]:
import logging
logging.basicConfig(filename="logs.log",format="%(asctime)s - %(message)s",level=logging.DEBUG,force=True)

In [6]:
sen1 = "This is an apple"

### Get the vector for a sentence

> Tokenize 
> For each token get the index from the vocabulary

In [7]:
# Read the vocab and merge rules

with open("/kaggle/input/tinystories-custom-bpe/merge_rules.pkl","rb") as f:
    merge_rules = pickle.load(f)
    
with open("/kaggle/input/tinystories-custom-bpe/vocab.pkl","rb") as f:
    vocab = pickle.load(f)

In [8]:
len(merge_rules),len(vocab)

(9786, 9840)

In [9]:
def tokenize(text,merge_rules):
    '''Return tokens from the text'''
    logging.info(f"Starting tokenization for the text -> {text}")
    text = text.lower() # our vocabulary is uncased.
    words = nltk.word_tokenize(text)
    
    ##preparing dict where word is the key and the tokens is its value
    word_dict = dict()
    for word in words:
        word_dict[word] = []
        for char in word:
            word_dict[word].append(char)
            
    logging.info("Starting to iterate through each merge rule")
    
    for merge_rule in merge_rules.keys():
        #go through each merge rule and tokenize each word from left to right
        for word in word_dict.keys():
            tokens = word_dict[word]
            idx=0
            while(idx<len(tokens)-1):
                pair = (tokens[idx],tokens[idx+1])
                if pair==merge_rule:
                    logging.info(f"merging for word {word}")
                    #merge the token of the word as per the merge rule
                    #if merged we dont increase the index of the tokens because the next pair should include the new pair and the next char
                    tokens = tokens[:idx]+[tokens[idx]+tokens[idx+1]]+tokens[idx+2:]
                    word_dict[word] = tokens
                else:
                    #if not merged then we slide the window over
                    idx = idx+1
        logging.info(f"After merge {word_dict}")
    return word_dict    
        

In [10]:
merge_rules[('t', 'h')]

'th'

In [11]:
tokenize(sen1,merge_rules)

{'this': ['this'], 'is': ['is'], 'an': ['an'], 'apple': ['apple']}

In [12]:
def sen_to_tensor(sen,vocab,merge_rules):
    '''Each sen will be converted to a vector where each token will be mapped to its index in vocab'''
    sen = sen.lower()
    token_dict = tokenize(sen,merge_rules)
    words = nltk.word_tokenize(sen)
    vocab = list(vocab)
    list_of_tokens = []
    for word in words:
        list_of_tokens.extend(token_dict[word])
    
    #find the index of the token in the vocab
    tensor = np.empty(len(list_of_tokens),dtype=int)
    for idx,token in enumerate(list_of_tokens):
        tensor[idx] = vocab.index(token)
    return tensor
        
    

In [13]:
sen_to_tensor(sen1,vocab,merge_rules)

array([4290, 1064, 9373, 5047])

In [14]:
def pos_embed_sen(sen_tensor,n=100,d=4):
    '''Given a sen tensor return its pos embed'''
    seq_len = len(sen_tensor)
    pos_embed_matrix = np.zeros((seq_len,d))
    
    for k in range(len(sen_tensor)):
        for i in range(0,int(d/2)):
            denom = np.power(n,((2*i)/d))
            pos_embed_matrix[k,2*i] = np.sin(k/denom)#for even embed dim
            pos_embed_matrix[k,2*i+1] = np.cos(k/denom)#for odd embed dim
    
    return pos_embed_matrix
        
    
    

In [15]:
tensor= sen_to_tensor(sen1,vocab,merge_rules)
pos_embed = pos_embed_sen(tensor)
pos_embed

array([[ 0.        ,  1.        ,  0.        ,  1.        ],
       [ 0.84147098,  0.54030231,  0.09983342,  0.99500417],
       [ 0.90929743, -0.41614684,  0.19866933,  0.98006658],
       [ 0.14112001, -0.9899925 ,  0.29552021,  0.95533649]])

## Merge with Token embeddings

In [16]:
#consider the token embeddings to be a random numpy matrix
def token_embed_sen(tensor,vocab_len,d=4):
    
    #torch will create a looup table of dim vocab_len*embedding_dim
    #at the time of output it will look up the embedding and return
    embed_layer = nn.Embedding(vocab_len,d)
    print(embed_layer.weight.shape)
  
    output = embed_layer(torch.tensor(tensor))
    
    #to only return the matrix without the grad
    return output.detach().numpy()

In [17]:
tensor_of_sen = sen_to_tensor(sen1,vocab,merge_rules)
token_embed = token_embed_sen(tensor,len(vocab))
token_embed

torch.Size([9840, 4])


array([[ 0.31746653,  0.14460814,  0.6741513 , -1.1949483 ],
       [ 0.30879948, -0.8313213 ,  0.6578424 ,  1.3326224 ],
       [ 0.00236675, -0.5804003 ,  1.2028182 ,  1.8941643 ],
       [ 0.21328416, -0.9833757 , -0.5708011 ,  1.4548188 ]],
      dtype=float32)

In [18]:
np.shape(token_embed),np.shape(pos_embed)

((4, 4), (4, 4))

In [19]:
#now lets add the pos and token embed to get the final embedding matrix
final_embed = np.add(token_embed,pos_embed)

final_embed.shape

(4, 4)